SELECT DEPARTMENT_ID 
	 , SUM(SALARY) 합계
	 , FLOOR(AVG(SALARY)) 평균
	 , COUNT(*) 인원수
  FROM EMPLOYEES
 WHERE SALARY > 5000
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID ASC; 

SELECT DEPARTMENT_ID 
	 , SUM(SALARY) 합계
	 , FLOOR(AVG(SALARY)) 평균
	 , COUNT(*) 인원수
  FROM EMPLOYEES
HAVING AVG(SALARY) > 5000
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID ASC;  