SELECT * FROM EMPLOYEES;
/*
 *	부서별 평균, 최대, 최소 급여를 집계한 DEPT_SALARY_STATICS 테이블 만들어 데이터 추가
 */
DROP TABLE DEPT_SALARY_STATICS;
CREATE TABLE DEPT_SALARY_STATICS
AS
SELECT DEPARTMENT_ID 부서
	 , FLOOR(AVG(SALARY)) AS 평균
	 , MAX(SALARY) 최대
	 , MIN(SALARY) 최소
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NOT NULL
 GROUP BY DEPARTMENT_ID;
SELECT * FROM DEPT_SALARY_STATICS ORDER BY 1;

/*
 *	직급별 평균, 최대, 최소 급여를 집계한 JOB_SALARY_STATICS 테이블 만들어 데이터 추가
 */
DROP TABLE JOB_SALARY_STATICS;
CREATE TABLE JOB_SALARY_STATICS
AS
SELECT JOB_ID 직급
	 , FLOOR(AVG(SALARY)) AS 평균
	 , MAX(SALARY) 최대
	 , MIN(SALARY) 최소
  FROM EMPLOYEES 
 WHERE JOB_ID IS NOT NULL
 GROUP BY JOB_ID;
SELECT * FROM JOB_SALARY_STATICS ORDER BY 1;

/*
 *	직급 ID에 'MGR'이 접미사로 붙은 JOB_SALARY_STATICS에 평균, 최대, 최소 급여를 +500 수정
 */
UPDATE JOB_SALARY_STATICS 
   SET 평균 = 평균 + 500
   	 , 최대 = 최대 + 500
   	 , 최소 = 최소 + 500
 WHERE 직급 LIKE '%MGR';
SELECT *
  FROM JOB_SALARY_STATICS
 WHERE 직급 LIKE '%MGR';

/*
 *	연도별 입사 인원을 파악하기 위한 HIRE_FOR_YEAR 테이블을 만들어 데이터 추가
 *	(인원 파악이 주목적이기 때문에 연도와 인원수만 저장할 수 있으면 됨)
 */
DROP TABLE HIRE_FOR_YEAR;
CREATE TABLE HIRE_FOR_YEAR
AS
SELECT EXTRACT(YEAR FROM HIRE_DATE) AS "입사 연도"
	 , COUNT(*) AS "입사 인원"
  FROM EMPLOYEES
 GROUP BY EXTRACT(YEAR FROM HIRE_DATE);
SELECT * FROM HIRE_FOR_YEAR;

/*
 *	부서별/직급별 평균, 최대, 최소 급여를 저장한 테이블에
 *	COMMISSION_PCT까지 반영한 데이터가 저장될 수 있도록 기존 정보 수정
 */
SELECT * FROM DEPT_SALARY_STATICS;
UPDATE DEPT_SALARY_STATICS
   SET (평균, 최대, 최소) = (SELECT FLOOR(AVG(SALARY * (1+ NVL(COMMISSION_PCT, 0))))
   								  , MAX(SALARY * (1+ NVL(COMMISSION_PCT, 0)))
   								  , MIN(SALARY * (1+ NVL(COMMISSION_PCT, 0)))
   							   FROM EMPLOYEES
   							  WHERE DEPARTMENT_ID IS NOT NULL
   							    AND DEPARTMENT_ID = 부서
 						   GROUP BY DEPARTMENT_ID);
 						  
SELECT * FROM JOB_SALARY_STATICS;
UPDATE JOB_SALARY_STATICS
   SET (평균, 최대, 최소) = (SELECT FLOOR(AVG(SALARY * (1+ NVL(COMMISSION_PCT, 0))))
   								  , MAX(SALARY * (1+ NVL(COMMISSION_PCT, 0)))
   								  , MIN(SALARY * (1+ NVL(COMMISSION_PCT, 0)))
   							   FROM EMPLOYEES
   							  WHERE JOB_ID IS NOT NULL
   							    AND JOB_ID = 직급
 						   GROUP BY JOB_ID);